name: model-training
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: Install dependencies
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          cd scripts/
          python cml_train_decision_trees.py
          
          echo "## MODEL METRICS" > report.md
          cat metrics.txt >> report.md

          echo "## Data vis" >> report.md
          cml-publish feature_importance.png >> report.md
          cml-publish confusion_matrix.png >> report.md

          cml-send-comment report.md